TrainingArguments: 
  num_train_epochs: 3
  warmup_steps: 500
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  weight_decay: 0.01
  logging_steps: 10
  eval_strategy: 'steps'
  eval_steps: 500
  save_steps: 5e-5
  gradient_accumulation_steps: 16
  report_to: 'none'
  

     